from snakemake.utils import Paramspace
import yaml

#def load_config(path):
#    with open(path, 'r') as stream:
#        config = yaml.safe_load(stream)
#    return config

import pandas as pd

configfile: "config/config.yaml"

module vpipe_sudan:
    snakefile: github("cbg-ethz/V-pipe", path="workflow/Snakefile", tag="v3.0.0.pre1")
    config: config["vpipe_sudan"]
    replace_prefix: {"results/": "results/sudan/"}

module vpipe_uganda:
    snakefile: github("cbg-ethz/V-pipe", path="workflow/Snakefile", tag="v3.0.0.pre1")
    config: config["vpipe_uganda"]
    replace_prefix: {"results/": "results/uganda/"}

use rule * from vpipe_sudan as vpipe_sudan_*
use rule * from vpipe_uganda as vpipe_uganda_*

ruleorder: vpipe_uganda_gunzip > vpipe_uganda_extract > vpipe_sudan_gunzip > vpipe_sudan_extract

rule all:
    input:
        rules.vpipe_uganda_all.input,
        rules.vpipe_sudan_all.input,
    default_target: True
