vpipe_sudan:
  general:
      aligner: "bwa"

  input:
      reference: resources/references/PQ268485.fasta # sequence from Sudan outbreak
      datadir: /cluster/work/bewi/members/lfuhrmann/HEV_project/data/
      read_length: 100
      paired: true
      samples_file: config/samples.tsv

  consensus_bcftools:
      max_coverage: 150000

  bwa_align:
      time: 600

  output:
      datadir: results_sudan
      snv: false
      local: false
      global: false
      visualization: false
      diversity: false
      QA: false

vpipe_uganda:
  general:
      aligner: "bwa"

    bwa_align:
        time: 600

  input:
      reference: resources/references/OQ077986.fasta # sequence from Uganda
      datadir: /cluster/work/bewi/members/lfuhrmann/HEV_project/data/
      read_length: 100
      paired: true
      samples_file: config/samples.tsv

  consensus_bcftools:
      max_coverage: 150000

  output:
      datadir: results_uganda
      snv: false
      local: false
      global: false
      visualization: false
      diversity: false
      QA: false
